<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishAot>true</PublishAot>
        <InvarientGlobalization>true</InvarientGlobalization>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\G2D\G2D.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets/*"/>
    </ItemGroup>

</Project>
