<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>0.1.2</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ppy.SDL3-CS" Version="2026.320.0"/>
        <PackageReference Include="ppy.SDL3_mixer-CS" Version="2026.320.0"/>
        <PackageReference Include="ppy.SDL3_ttf-CS" Version="2026.320.0"/>
        <PackageReference Include="StbImageSharp" Version="2.30.15"/>
        <PackageReference Include="Vortice.Vulkan" Version="3.2.1"/>
        <PackageReference Include="Vortice.VulkanMemoryAllocator" Version="1.7.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\G2D.Mathematics\G2D.Mathematics.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\**"/>
    </ItemGroup>
</Project>
