<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <ApplicationIcon>Assets\Images\logo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\G2D\G2D.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\**"/>
    </ItemGroup>
</Project>
